DCNJ-Uket/Uket-BE-Kotlin

- build.gradle.kts
- src/main/kotlin/uket/domain/user/enums/UserRole.kt
- src/main/kotlin/uket/domain/user/service/UserService.kt
- src/main/kotlin/uket/modules/redis/RedisValues.kt
- src/main/kotlin/uket/modules/redis/aop/AopForTransaction.kt
- src/main/kotlin/uket/modules/redis/aop/DistributedLock.kt
- src/main/kotlin/uket/modules/redis/aop/DistributedLockAop.kt
- src/main/kotlin/uket/modules/redis/config/RedisConfig.kt
- src/main/kotlin/uket/modules/redis/properties/RedisProperties.kt
- src/main/kotlin/uket/modules/redis/service/RotateTokenService.kt
- src/main/kotlin/uket/modules/redis/util/CustomSpringELParser.kt
- src/main/kotlin/uket/modules/redis/util/RedisValues.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/test/kotlin/uket/service/RotateTokenServiceTest.kt
- src/test/resources/application.yml
- Redis Module migration을 진행했습니다.
- 
-
> [UKET-66] Redis Module Migration

- .github/CODEOWNERS
- .github/workflows/uket-cd.yml
- .github/workflows/uket-ci.yml
- Dockerfile
- build.gradle.kts
- docker/run-java.sh
- src/main/kotlin/uket/api/AdminController.kt
- src/main/kotlin/uket/domain/user/enums/UserRole.kt
- src/main/kotlin/uket/domain/user/service/UserService.kt
- src/main/kotlin/uket/modules/redis/RedisValues.kt
- src/main/kotlin/uket/modules/redis/aop/AopForTransaction.kt
- src/main/kotlin/uket/modules/redis/aop/DistributedLock.kt
- src/main/kotlin/uket/modules/redis/aop/DistributedLockAop.kt
- src/main/kotlin/uket/modules/redis/config/RedisConfig.kt
- src/main/kotlin/uket/modules/redis/properties/RedisProperties.kt
- src/main/kotlin/uket/modules/redis/service/RotateTokenService.kt
- src/main/kotlin/uket/modules/redis/util/CustomSpringELParser.kt
- src/main/kotlin/uket/modules/redis/util/RedisValues.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/test/kotlin/uket/service/RotateTokenServiceTest.kt
- src/test/resources/application.yml
- #7 이 squash and merge 되지 않은 것 같아 PR을 다시 날렸습니다
- 
-
> RE : [UKET-66] Redis Module Migration

- build.gradle.kts
- src/main/kotlin/modules/qrcode/properties/QRCodeProperties.kt
- src/main/kotlin/modules/qrcode/provider/QRCodeProvider.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/test/kotlin/uket/service/RotateTokenServiceTest.kt
- src/test/resources/application.yml
- qr module migration을 진행했습니다.
- 
-
> qrcode module migration

- build.gradle.kts
- src/main/kotlin/common/ControllerAdvice.kt
- src/main/kotlin/modules/slack/ApplicationListener.kt
- src/main/kotlin/modules/slack/SlackGateway.kt
- src/main/kotlin/modules/slack/dto/ErrorReportDto.kt
- src/main/resources/application-dev.yml
- src/test/resources/application.yml
- slack-module migration을 진행했습니다.
- 
-
> slack-module migration

- build.gradle.kts
- src/main/kotlin/modules/s3/config/S3Config.kt
- src/main/kotlin/modules/s3/properties/S3Properties.kt
- src/main/kotlin/modules/s3/service/S3Service.kt
- src/test/resources/application.yml
- aws s3 관련 모듈 migration을 진해했습니다.
- 
-
> s3-module migration

- src/main/kotlin/api/admin/OrganizationController.kt
- src/main/kotlin/domain/admin/repository/OrganizationRepository.kt
- src/main/kotlin/domain/admin/service/OrganizationService.kt
- 단체 조회시에 어드민에 등록 되지 않은 이용 가능한 단체만 조회되도록 API 수정을 진행했습니다.
- 
-
> [UKET-91] 어드민 단체 조회 API 수정

- src/main/kotlin/api/admin/request/RegisterUketEventRequest.kt
- src/main/kotlin/domain/eventregistration/EventData.kt
- src/main/kotlin/domain/eventregistration/entity/BannerRegistration.kt
- src/main/kotlin/domain/eventregistration/entity/EventRegistration.kt
> [UKET-94] 배너 및 결제정보 추가

- src/main/kotlin/api/admin/AdminTicketController.kt
- src/main/kotlin/api/admin/dto/EventNameDto.kt
- src/main/kotlin/api/admin/response/FilterEventResponse.kt
- src/main/kotlin/domain/reservation/repository/TicketRepository.kt
- src/main/kotlin/domain/reservation/service/TicketService.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcher.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByCreatedAt.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByEventRoundDateTime.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByModifiedAt.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByPhoneNumber.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByStatus.kt
- src/main/kotlin/domain/reservation/service/search/TicketSearcherByUserName.kt
- src/main/kotlin/domain/uketevent/repository/UketEventRepository.kt
- src/main/kotlin/domain/uketevent/service/UketEventService.kt
- src/main/kotlin/facade/EnterUketEventFacade.kt
- 불필요한 eventRoundId pathvariable 삭제 및 filtering에 필요한 events 목록 조회 API를 구현했습니다.
- 
-
> hotfix: ticket search pathvariable 삭제

- .editorconfig
- src/main/kotlin/uket/api/admin/EventRegistrationController.kt
- src/main/kotlin/uket/domain/StatusState.kt
- src/main/kotlin/uket/domain/eventregistration/entity/EventRegistrationStatus.kt
- src/main/kotlin/uket/domain/eventregistration/service/EventRegistrationService.kt
- src/main/kotlin/uket/domain/eventregistration/service/EventRegistrationStatusState.kt
- src/main/kotlin/uket/domain/eventregistration/service/EventRegistrationStatusStateResolver.kt
- src/main/kotlin/uket/facade/eventregistration/검수완료EventRegistrationStatusState.kt
- src/main/kotlin/uket/facade/eventregistration/검수진행EventRegistrationStatusState.kt
- src/main/kotlin/uket/facade/eventregistration/등록완료EventRegistrationStatusState.kt
- src/main/kotlin/uket/facade/eventregistration/등록취소EventRegistrationStatusState.kt
- src/main/kotlin/uket/facade/eventregistration/행사완료EventRegistrationStatusState.kt
- 상태변경 가능한 상태 정의 및 각 상태별로 수행해야할 로직이 정의될 수 있도록 구현했습니다.
- 이후 TicketStatus도 동일하게 구현 예정입니다.
- execute() 에 각 상태별 수행해야하는 로직 구현해주시면 됩니다.
- 혹시 구조가 이해안된다면 편하게 말씀 부탁드려용~
> [UKET-123] 행사등록 상태변경 구조 작성

- src/main/kotlin/uket/api/admin/request/RegisterUketEventRequest.kt
- src/main/kotlin/uket/api/admin/response/UketRegistrationEventResponse.kt
- src/main/kotlin/uket/domain/eventregistration/EventData.kt
- src/main/kotlin/uket/domain/eventregistration/entity/EntryGroupRegistration.kt
- src/main/kotlin/uket/domain/eventregistration/entity/EventRegistration.kt
> [UKET-135] 행사 등록 API 수정사항 반영

- src/main/kotlin/uket/api/admin/EventRegistrationController.kt
- 행사 등록 API 버그 fix했습니다.
- path variable로 organizationId를 받도록 수정
- 
-
> [UKET-144] 행사 등록 API 버그 fix

- src/main/kotlin/uket/api/admin/AdminController.kt
- src/main/kotlin/uket/api/admin/request/RegisterAdminPasswordRequest.kt
- src/main/kotlin/uket/domain/admin/entity/Admin.kt
- src/main/kotlin/uket/domain/admin/service/AdminService.kt
- src/main/kotlin/uket/facade/AdminAuthEmailFacade.kt
- src/test/kotlin/uket/domain/DomainEntityTest.kt
- src/test/kotlin/uket/domain/admin/service/AdminServiceTest.kt
- 어드민 회원가입 시, 전화번호 추가했습니다.
- N/A
- N/A
> [UKET-141] 어드민 회원가입 시, 전화번호 추가

- src/main/kotlin/uket/api/admin/AdminController.kt
- src/main/kotlin/uket/api/admin/request/RegisterAdminPasswordRequest.kt
- src/main/kotlin/uket/api/admin/request/SendEmailRequest.kt
- src/main/kotlin/uket/domain/admin/dto/AdminWithOrganizationDto.kt
- src/main/kotlin/uket/domain/admin/dto/RegisterAdminWithoutPasswordCommand.kt
- src/main/kotlin/uket/domain/admin/entity/Admin.kt
- src/main/kotlin/uket/domain/admin/service/AdminService.kt
- src/main/kotlin/uket/domain/eventregistration/entity/EventRegistration.kt
- src/main/kotlin/uket/facade/AdminAuthEmailFacade.kt
- src/test/kotlin/uket/domain/DomainEntityTest.kt
- src/test/kotlin/uket/domain/admin/service/AdminServiceTest.kt
- 행사 등록 API 문의처 type 필드 추가(전화번호, 기타) / 어드민 사용자 회원가입 메일 발송 API 전화번호 필드 추가
- 
-
> [UKET-160] 행사 등록 API 문의처 type 필드 추가(전화번호, 기타) / 어드민 사용자 회원가입 메일 발송 API 전화번호 필드 추가

- src/main/kotlin/uket/api/user/EventController.kt
- src/main/kotlin/uket/api/user/response/EventDetailResponse.kt
- 행사 상세 정보 조회 화면이 변경되면서 필요한 응답 데이터를 추가했습니다
-
- 
-
> [UKET-137] 행사 상세 정보 조회 응답 데이터 추가

- src/main/kotlin/uket/api/user/UserController.kt
- src/main/kotlin/uket/api/user/response/UserInfoResponse.kt
- 유저 정보 조회 API 마이그레이션 진행했습니다
-
- 
-
> [UKET-166] 유저 정보 조회 API 마이그레이션

- src/main/kotlin/uket/api/user/UserController.kt
- src/main/kotlin/uket/api/user/response/UserDeleteResponse.kt
- 유저 회원탈퇴 API 마이그레이션 진행했습니다.
테스트 결과
- 
-
> [UKET-172] 유저 회원탈퇴 API 마이그레이션

- src/main/kotlin/uket/facade/eventregistration/검수완료EventRegistrationStatusState.kt
> [UKET-177] 등록완료 -> 검수완료 상태 변경 추가

- src/main/kotlin/uket/api/user/response/UserTicketResponse.kt
> style : 티켓 상태 String으로 변경

- src/main/kotlin/uket/api/admin/EventRegistrationController.kt
- src/main/kotlin/uket/api/admin/request/RegisterUketEventRequest.kt
- src/main/kotlin/uket/api/admin/response/UketEventRegistrationSummaryResponse.kt
- src/main/kotlin/uket/domain/eventregistration/EventData.kt
- src/main/kotlin/uket/domain/eventregistration/entity/EventRegistration.kt
- 행사 조회 시 티켓 수량 제한이 누락되어 조회가 되지않던점을 수정했습니다.
- 
-
> hotfix: 행사 조회시 티켓 수량 제한 누락 수정

- src/main/kotlin/uket/api/admin/AdminController.kt
- src/main/kotlin/uket/api/admin/request/CheckRegisterExpiredRequest.kt
- src/main/kotlin/uket/api/admin/response/CheckRegisterExpiredResponse.kt
- src/main/kotlin/uket/auth/config/SecurityConfig.kt
- src/main/kotlin/uket/facade/AdminAuthEmailFacade.kt
- 어드민 회원가입을 위한 email token이 만료되었는지 여부를 확인할 수 있는 기능을 추가했습니다.
- 
-
> [UKET-214] 어드민 회원가입 링크 만료 여부 확인 API 추가

- src/main/kotlin/uket/api/user/EventController.kt
- src/main/kotlin/uket/api/user/response/EventDetailResponse.kt
- src/main/kotlin/uket/domain/uketevent/service/UketEventRoundService.kt
- src/main/kotlin/uket/facade/UketEventFacade.kt
- 행사 상세 정보 API 조회 시 ticketingStatus를 응답 response에 추가했습니다.
- 
-
> hotfix: 행사 상세 정보 ticketingStatus 추가

- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- QR 코드 유효시간을 3분으로 변경했습니다.
- 
-
> [UKET-236] QR 코드 유효시간 변경

- src/main/kotlin/uket/api/admin/EventRegistrationController.kt
- src/main/kotlin/uket/api/admin/response/UketEventRegistrationSummaryResponse.kt
- 행사 등록 목록 조회 시, organization name 설정
- 
-
> [UKET-240] 행사 등록 목록 조회 시, organization name 설정

- src/main/kotlin/uket/facade/TicketingFacade.kt
- 인당 티켓 제한 개수가 없는 경우 분기처리
- 
-
> [UKET-241] 인당 티켓 제한 개수가 없는 경우 분기처리

- src/main/kotlin/uket/api/user/response/ReservationInfoResponse.kt
- 예매 정보 조회 시, 인당 티켓 제한 수량 추가
- 
-
> [UKET-244] 예매 정보 조회 시, 인당 티켓 제한 수량 추가

- src/main/kotlin/uket/api/user/TicketController.kt
- src/main/kotlin/uket/api/user/response/TicketingResponse.kt
- 예매 응답에서, 계좌 정보가 누락되어있던 점을 수정했습니다
- 
-
> [UKET-250] 예매 시, 계좌 정보 제공

- src/main/kotlin/uket/api/user/UserController.kt
- src/main/kotlin/uket/api/user/response/UserTicketResponse.kt
- src/main/kotlin/uket/domain/payment/service/PaymentService.kt
- src/main/kotlin/uket/facade/FindUserTicketsFacade.kt
- 유저 티켓 목록 조회 시 누락되어있던 응답을 추가했습니다.
- 
-
> hotfix: 유저 티켓 목록 조회 시 누락된 응답 추가

- src/main/kotlin/uket/facade/TicketingFacade.kt
- src/main/kotlin/uket/facade/message/PaymentInformationMessageSendService.kt
> hotfix : 알림톡 티켓 전체 가격이 아닌 티켓 하나 가격으로 표시되는 문제 수정

- src/main/kotlin/uket/facade/TicketingFacade.kt
- src/main/kotlin/uket/facade/message/PaymentInformationMessageSendService.kt
> dev to main
